src/components/Common/Editor/EditorToolbar/index.ts, src/components/Layout/index.tsx
Proposed correction for bad overflow usage in header resulting in a display bug on safari, and an unwanted scroll bar appearance on Safari and chrome, https://github.com/blinko-space/blinko/issues/407
Also proposal for adding indent and outdent button on mobile in response to https://github.com/blinko-space/blinko/issues/400
=> Bad overflow usage in header resulting in a display bug and indent/outdent buttons on editor

src/components/BlinkoSettings/PerferSetting.tsx
Fix #417 bug, update PerferSetting to include maxHomePageWidth in useEffect dependencies
=> Fix #417 the maximum width status of the home page being saved

src/components/BlinkoAi/aiTag.tsx
enhancement: #390 change default state of isInsertBefore to false in AiTag component
=> enhancement 390 When tagging an article with ai, it is automatically selected as the tag post.

src/store/aiStore.tsx, src/store/blinkoStore.tsx
fix #430 Chat history persisting between different user accounts
1. AiStore eventBus.on('user:singout', do clear)
2. BlinkoStore clear tmp edit info
=> fix #430 Chat history persisting between different user accounts

src/components/BlinkoEditor/index.tsx, src/components/Common/Editor/Toolbar/NoteTypeButton/index.tsx, src/components/Common/Editor/editorStore.tsx, src/components/Common/Editor/hooks/useEditor.ts, src/components/Common/Editor/index.tsx, src/components/Common/Editor/type.ts, src/server/types.ts
fix #444  Refactor: decouple `noteType`  move to the Editor initialization.
=> fix #444 Editing a ‘Note’ that’s selected when viewing by tag changes the note to a Blinko

src/server/plugins/ai.ts, src/server/plugins/memos.ts, src/server/routers/note.ts
Currently, when AI is enabled, the time of notes imported from memos is changed to the current time. Rebuilding the index will also cause the time of notes to change to the current time. I think this may be a mistake, because the update time of the note should not be refreshed when the content of the note has not changed.
This PR solves this problem by simply and crudely re-assigning updatedAt, because I assume that updatedAt is only used to display on the user interface. If the updatedAt field doesn't just represent when the note content was updated, then maybe we need to add another field to disambiguate it.
_I've proceeded with this implementation to facilitate my data migration during the holiday period. I apologize for not initiating a discussion beforehand, but I believe this fix …
=> fix(ai): Preserve original updatedAt timestamp during memos import and reindexing

src/server/plugins/memos.ts
Currently when importing from Memos, comments are imported as normal notes. This PR realizes the distinction between comments and notes, and supports importing comments.
The comment section distinguishes whether it is the original memo author. If it is the original memo author, the comment author is set to the current user, otherwise it is a visitor.
---
目前从 Memos 导入时，评论会被当作普通 note 导入。这个 PR 实现了评论和笔记的区分，并支持导入评论。
评论部分区分了是否是原 memo 作者。如果是原memo 作者，评论作者就设为当前用户，否则是游客身份。
=> Feat(memos) support correct import comments

src/server/routers/config.ts
This PR just exposes 'customBackgroundUrl' from trpc.config.list to achieve the effect described in the documentation.
=> Fix(server/config)  custom background url not work

src/server/routers/note.ts, src/store/blinkoStore.tsx
For highlighted operations on blinkos or notes, the corresponding `note.type` in the database would be assigned `0`, causing notes to unexpectedly become `BLINKO`.
This PR fixes the issue by adjusting default values for frontend/backend _upsertNote_ operations. I've verified this PR by checking all interfaces that call the upsert method wherever possible - it should work properly. 
I'm not sure if this modification conflicts with your original intentions, so please feel free to handle this PR as you see fit.
=> fix(note): FE accidentally turned into blinko after operating on note

src/store/plugin/pluginManagerStore.ts
A very small fix that wiped out a reported error.
However, I feel as though the part of the code that was changed doesn't seem to be of much use if it's not dealing with a special case.
https://github.com/blinko-space/blinko/commit/0e841613878451124469c3cbef133a0e33de2d60#diff-1ebd9ecac7133ad8e4e7bbc8d483d0482224b0991ca7e431dc1bce755f61d1bbL221-L223
=> fix(plugin-manager): correct plugin setting panel flag assignment

src/components/BlinkoCard/cardBlogBox.tsx
Propose change: set inside article content, an image link called `cover` - which will be then thread as cover for cardBlogBox.
Before:
After:
=> Articule cover image based on markdown content (cover image) if no explicit cover is provided

src/server/routers/tag.ts
目前点击删除标签和笔记按钮，仅会将标签下的内容放入回收站，但并未删除标签。
---
Currently clicking on the delete tab and notes button only puts the contents of the tab into the recycle bin, but does not delete the tab.
---
Currently clicking the Delete Tags and Notes button will only place the content under the tags into the Recycle Bin, but the tags are not deleted.
---
Currently clicking on the delete tab and notes button only puts the contents of the tab into the recycle bin, but does not delete the tab.
=> fix: delete tags and botes button undelete tags Issue || fix: delete tags and bottles button undelete tags Issue

app/api/file/upload/route.ts
中文文件名不会出现乱码的情况
---
There will be no garbled Chinese file name
=> fix: decode filename from binary to UTF-8 in file upload

src/components/Layout/index.tsx
当前版本将”关闭每日回顾“开启后，依然会显示每日回顾的入口，原因是前端未根据配置信息控制入口button的显示
---
The current version will "Close Daily Review" after the "Daily Review" is turned on, the entrance for the daily review will still be displayed, because the front-end does not control the display of the entrance button based on the configuration information
=> fix: conditionally render button based on daily review configuration

src/components/BlinkoAddButton/index.tsx
当H5 底部 bar 出来时，让 bottom 往上挪一点，避免被遮挡
When the H5 bottom bar appears, move the bottom up slightly to avoid being obscured.
***
=> feat(BlinkoAddButton): When the H5 bottom bar appears, move the bottom up slightly to avoid being obscured.

src/components/BlinkoAddButton/index.tsx
#619 
fix(BlinktoAddButton): Hide the previous editing and AI buttons, temporarily keep them, in case they will be expanded for use later.
=> fix(BlinktoAddButton): #619,Hide the previous editing and AI buttons

app/src/components/BlinkoSettings/AiSetting.tsx
Fixes issue #665 by making sure the models list path is correct
=> Ensures that the ollama path for the list of models is `/api/tags`

server/index.ts
The server now binds to all network interfaces (`0.0.0.0`) instead of only `localhost`. See https://www.npmjs.com/package/vite-express?activeTab=readme for details.
=> Bind to all network interfaces (was: only localhost)

app/vite.config.ts, server/routerExpress/auth/index.ts
**Changes**:  
1. Service Worker Configuration  
- Added `navigateFallbackDenylist` to exclude auth API routes from caching  
- Prevents service worker from intercepting `/api/auth/` endpoints  
2. OAuth State Parameter Fix  
- Implemented explicit state generation with 10-character random string  
- Uses `Math.random().toString(36).substring(2, 12)` for sufficient entropy  
- Meets Authelia's minimum 8-character state requirement  
This PR can fix the issue where I couldn't log in through Authelia on my Blinko instance, though it might also resolve #670.
=> Fix service worker caching and enhance OAuth state security

app/vite.config.ts
The /api/file/* path is currently intercepted by the service worker, which is causing several issues. It should be excluded from the service worker's scope.
=> fix: navigateFallbackDenylist `/api/*`

server/routerTrpc/note.ts
在容器运行过程中观察到VoyageAI API调用失败的错误日志：
```
Error in enhanceQuery: pN [AI_APICallError]: Bad Request
at /app/server/index.js:3032:13807
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async K7l (/app/server/index.js:3032:12515)
at async c$l.doEmbed (/app/server/index.js:3032:75459)
...
cause: undefined,
url: 'https://api.voyageai.com/v1/embeddings',
requestBodyValues: {
input: [ '' ],  // 空字符串导致400错误
model: 'voyage-3.5',
input_type: undefined,
truncation: undefined,
output_dimension: undefined,
output_dtype: undefined
},
statusCode: 400
```
在 `server/routerTrpc/note.ts:110` 中：
```typescript
return await AiService.enhanceQuery({
query: searchText?.replace(/@/g, "")!,
ctx,
});
```
当用户搜索的文本只包含 `@` 符号时，`replace(/@/g, '')` 会产生空字符串，然后传递给EmbeddingAPI。API拒绝处理空输入，返回400 …
=> fix: prevent empty string being sent to embeddings API

app/public/locales/fr/translation.json
The French translation for "Todo" was incorrectly set to "Procuration".  
This PR updates it to "Tâches", which is the correct and natural wording for tasks in French.
=> Docs: update French translation of todo to Tâches instead of Procuration
